title: Nirav Daphtary # your name (or website title) here
logo: "images/ND profile pic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A biomedical engineer with a strong foundation in data analytics and a passion for exploring the intersection of technology, health, and innovation.<br>
  Iâ€™m driven by a curiosity to understand complex systems, identify patterns, and translate data into actionable insights.<br>
  ğŸ”¬ My work spans biomedical research, system development, and advanced data analysis.<br>
  ğŸ“Š I enjoy working on projects that bring together science, engineering, and real-world impact.<br>
  ğŸº Outside the lab and code editor, Iâ€™m a dedicated homebrewer and lifelong martial artist â€” always striving for precision, discipline, and creativity in all pursuits.<br><br>
  
 
  <a href="https://www.linkedin.com/in/niravdaphtary/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
